services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=NexusDb
    ports:
      - "5435:5432"  # <--- CHANGED HOST PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always