version: "3.8"

services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=NexusDb
    ports:
      - "5432:5432"
    volumes:
      - nexus-pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  nexus-pgdata:
